image:
  repository: forgerock-docker-public.bintray.io/forgerock/amster
  #repository: gcr.io/engineering-devops/amster
  tag: 6.5.0
  pullPolicy: Always
  
config:
  importPath: /git/config/6.5/cdm/m-cluster/am
  exportPath: /tmp/amster

ctsStores: ctsstore-0.ctsstore:1389
ctsPassword: password

domain: .example.com

userStore:
  host: userstore-0.userstore:1389

